= Go Service Components
ifdef::env-github[]
:imagesdir:
https://raw.githubusercontent.com/leaf-ai/go-service/main/docs/artwork
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]

:Revision: 0.0.1-main-aaaagqacvoy

:source-highlighter: coderay

:toc:
:toc-placement!:

This document describes a number of components exported by this package that are intended for use in the implementation of services within a service mesh or deployed using a managed platform.

This document is aimed at an audience with development and deployment skills who desire to implement services using the Go computer language.

The Go Service Components (GSC) are currently used within the Cognizant LEAF environment and its associated StudioML compute platform.

toc::[]

== Setup

[source,bash]
 ---------------------------------------------------------------------
sudo snap install docker
sudo apt-get install source-highlight

mkdir ~/project
cd ~/project
export GOPATH=`pwd`
export PATH=$GOPATH/bin:$PATH
mkdir -p src/github.com/leaf-ai
cd src/github.com/leaf-ai
git clone https://github.com/leaf-ai/go-service.git
cd go-service
mkdir -p $GOPATH/bin
go get github.com/karlmutch/petname
go install github.com/karlmutch/petname/cmd/petname
wget -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.15.1/semver-linux-amd64
wget -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.15.1/stencil-linux-amd64
chmod +x $GOPATH/bin/semver
chmod +x $GOPATH/bin/stencil
 ---------------------------------------------------------------------

Copyright © 2021 The Go Service Components Authors. All rights reserved. Issued under the Apache 2.0 License.
