= Go Service Components
ifdef::env-github[]
:imagesdir:
https://raw.githubusercontent.com/karlmutch/go-service/main/docs/artwork
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]

:Revision: 0.0.4

:source-highlighter: coderay
:source-language: sh

:toc:
:toc-placement!:

This project is a fork of the github.com/leaf-ai/go-service project.

This document describes a number of components exported by this package that are intended for use in the implementation of services within a service mesh or deployed using a managed platform.

This document is aimed at an audience with development and deployment skills who desire to implement services using the Go computer language.

The Go Service Components (GSC) are currently used within the Cognizant LEAF environment and its associated StudioML compute platform.

toc::[]

== Setup

[source]
----
sudo snap install docker
sudo apt-get install source-highlight

mkdir ~/project
cd ~/project
export GOPATH=`pwd`
export PATH=$GOPATH/bin:$PATH
mkdir -p src/github.com/karlmutch
cd src/github.com/karlmutch
git clone https://github.com/karlmutch/go-service.git
cd go-service
mkdir -p $GOPATH/bin
wget -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.17.0-rc.8/semver_0.17.0-rc.8_linux-amd64
wget -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.17.0-rc.8/stencil_0.17.0-rc.8_linux-amd64
chmod +x $GOPATH/bin/semver
chmod +x $GOPATH/bin/stencil
go get github.com/alvaroloes/enumer@455e9a94796c0e108c38e253b67307736fc4b200
----

stencil -supress-warnings < Dockerfile | docker build --network=host -

== Developer tooling

rancher desktop
go-mod-upgrade
gopls
vim-go
k9s vladimir
trvy
Fairwindows Pluto


Copyright © 2021-2023 The Go Service Components Authors. All rights reserved. Issued under the Apache 2.0 License.
